on:
  pull_request:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

name: "Cover It Up v2"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  coveritup:
    strategy:
      matrix:
        go-version: [latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}
      - name: Setup Node.js ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Setup Node.js ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"

      - name: NPM install
        working-directory: app/frontend
        run: npm install
      - name: NPM build
        working-directory: app/frontend
        run: npm run build

      - name: Go Build
        working-directory: app
        run: go mod tidy;go build -ldflags '-s -w' -o main main.go
      # - name: Go Lint
      #   working-directory: app
      #   run: golangci-lint run ./...
      - name: Go Test
        working-directory: app
        run: go test -race -v ./... -count=1
